name: Build

on: [push]

jobs:
  build:


    strategy:
      matrix:
        version:
          #- 1.34.0
          #- stable
          #- beta
          - nightly
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        features:
          - --all-features
          - --no-default-features

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Install toolchain
      run: |
        rustup install --profile minimal ${{ matrix.version }}
        rustup default ${{ matrix.version }}
    - name: Run tests
      run: cargo test --verbose ${{ matrix.features }}
